export {default as Header}    from './Header/Header'
export {default as Container} from './Container/Container'
export {default as Footer}    from './Footer/Footer'
export {default as Men}       from './Men/Men'
export {default as Women}     from './Women/Women'
export {default as Kids}      from './Kids/Kids'